feat: add v1.0.1

diff --git a/bin/ctxos-update b/bin/ctxos-update
--- a/bin/ctxos-update
+++ b/bin/ctxos-update
@@ -14,7 +14,7 @@ if [[ -z $CTXOS_UPDATE_LOGGED ]]; then
   exec env CTXOS_UPDATE_LOGGED=1 script -qefc "$script_command" "/tmp/ctxos-update.log"
 fi
 
-trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://ctxos.org/discord\033[0m"' ERR
+trap 'echo ""; echo -e "\033[0;31mSomething went wrong during the update!\n\nPlease review the output above carefully, correct the error, and retry the update.\n\nIf you need assistance, get help from the community at https://ctxos.github.io/discord\033[0m"' ERR
 
 if [[ $1 == "-y" ]] || ctxos-update-confirm; then
   ctxos-snapshot create || (($? == 127))
